/* eslint-disable import/prefer-default-export */
export const TestData = {
  list1: [{
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }],
  list2: [{
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }],
  list3: [{
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }, {
    comment: 'Hello',
    username: 'Jane',
    creation_date: '2022-05-19',
  }],
};